host: localhost
port: 3306
database: tokens
username: root
password: password
table: player_data
#Upgrades values that change amount you get from the upgrade
s1: 0.10
s2: 0.20
s3: 0.30
f1: 20
f2: 30
f3: 50
l1: 1.5
l2: 2.0
l3: 3.0
fu1: 3
fu2: 4
fu3: 6
b1: 3
b2: 4
b3: 5
#Upgrade price values
spawner1: 10
spawner2: 30
spawner3: 50
farm1: 10
farm2: 30
farm3: 40
loot1: 10
loot2: 30
loot3: 40
furnace1: 5
furnace2: 10
furnace3: 15
brewing1: 10
brewing2: 20
brewing3: 30
claimblock: 5
rankupgrade1: 50
rankupgrade2: 100
rankupgrade3: 150